some workflow fixes
npm packaging - CI/CD

basic deployment pipeline

basic deployment pipeline

basic deployment pipeline

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,28 +1,41 @@
-name: Unit Tests
+name: Deploy to NPM
 
 on:
   push:
-    branches: [npm-packaging]
+    # If you add a branch here, you **MUST** create a branch rule in Github settings
+    branches: ['*.*.x', '*.x', 'main', 'next', 'next-major', 'beta', 'alpha']
 
   workflow_dispatch: # trigger manually
 
 jobs:
-  unit_tests:
-    runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        node-version: [18.x, 20.x]
-
+  # Gihub Actions do not allow regex validation for numbers in *.*.x branch names
+  validate_branch_name:
+    runs-on: 'self-hosted-ubuntu-22-04-regular-x64'
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-      - name: Setup Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
+      - name: Validate branch name
+        run: |
+          branch_name=$(echo $GITHUB_REF | cut -d'/' -f3)
+          if [[ $branch_name =~ ^[0-9]+(\.[0-9]+)?\.x$ ]] || [[ $branch_name == "main" ]] || [[ $branch_name == "next" ]] || [[ $branch_name == "next-major" ]] || [[ $branch_name == "beta" ]] || [[ $branch_name == "alpha" ]]; then
+            echo "Branch name is valid"
+          else
+            echo "Branch name is invalid"
+            exit 1
+          fi
 
-      - run: npm ci
+  code_validation:
+    needs: [validate_branch_name]
+    uses: ./.github/workflows/code-validation.yaml
 
-      - run: npm run test
+  unit_tests:
+    needs: [validate_branch_name]
+    uses: ./.github/workflows/unit-tests.yaml
+
+  npm_release:
+    needs: [code_validation, unit_tests]
+    uses: ./.github/workflows/release.yaml
+    secrets:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
